modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="golf_it"
version="1.0.0"
displayName="Golf It"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Jo"

[[dependencies.golf_it]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




