modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="golf_it"
version="0.3.1"
displayName="GolfCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/joao44289/GolfCraft"
authors="joao44289"
description='''
A bad attempt at a minecraft gold mod.
'''

[[dependencies.golf_it]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




